image/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    # path('create/', views.create, name='create'),
    path('store/', views.store, name='store'),
    # path('login/', views.user_login, name='login'),
    # path('logout/', views.user_logout, name='logout'),
    # path('register/', views.register, name='register'),
    # path('profile/', views.profile, name='profile'),
    # path('show/', views.show_emp, name='show-emp'),
    # path('edit/<int:pk>', views.edit_emp, name='edit-emp'),
    path('delete/<id>', views.delete, name='delete'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('login/', TemplateView.as_view(template_name='user/login.html'), name='login'),
    
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('image/', include(('image.urls', 'image'), namespace='image'))
    
]

user/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('store/', views.store, name='store'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    # path('show/', views.show_emp, name='show-emp'),
    # path('edit/<int:pk>', views.edit_emp, name='edit-emp'),
    # path('remove/<int:pk>', views.remove_emp, name='remove-emp'),
]

image/models.py
from django.db import models

# Create your models here.
class  Image(models.Model):
    # image = models.ImageField(upload_to='media/')
    id = models.AutoField(primary_key= True)
    author = models.IntegerField()
    status = models.IntegerField(default=1)
    salt = models.IntegerField()
    title = models.CharField(max_length=255, default='NULL')
    filename = models.CharField(max_length=255, default='NULL')
    extension = models.CharField(max_length=5, default='NULL')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now=True)

image/views.py
from django.shortcuts import render, redirect
from .models import Image
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages #import messages
from django.core.files.storage import FileSystemStorage
import os, secrets, datetime
from testproject.helpers import HelperClass
from django.core.paginator import Paginator

def index(request):
    data=Image.objects.all().order_by("-id")
    paginator = Paginator(data, per_page=2)
    page = request.GET.get('page', 1)
    page_object = paginator.get_page(page)
    for item in page_object:
        item.src = HelperClass.genrate_image_path(item)
    context = {"page_obj": page_object}
    # HelperClass.genrate_image_path(data)
    return render(request,'image/index.html', context)

# def create(request):
#     return render(request,'user/create.html')

def store(request):
    if request.method=='POST':
        image = request.FILES['image']
        title = request.POST.get('title', '')
        # os.chmod('media/photos', 755)

        filename, file_extension = os.path.splitext(image.name)
        secret_range  = secrets.SystemRandom()
        salt=secret_range.randrange(100000, 999999)
        if not title:
            title = filename
        obj = Image(author=request.user.id, title=title,filename=image.name, salt=salt, status=1, extension=file_extension)
        obj.save()
        date = obj.created_at
        path ='media/files/images/'+str(date.year)+'/'+str(date.month)+'/'+str(date.day)+'/'+str(date.strftime("%f"))+'-'+str(obj.salt)+'/'+str(date.year)+str(date.month)+str(date.day)+'_'+str(date.strftime("%f"))+'-'+str(obj.salt)
        # path ='media/files/images/'+date.year+'/'+date.month+'/'+date.day+'/'+date.strftime("%f")+'-'+obj.salt+'/'+date.year+date.month+date.day+'_'+date.strftime("%f")+'-'+obj.extension
        fs =FileSystemStorage(location=path)
        uploadfilename = fs.save((str(date.year)+str(date.month)+str(date.day)+'_'+str(date.strftime("%f"))+'-'+str(obj.salt)+'.'+file_extension),image)
        # dd(  path)
        # object = Image()
        # object.save()
    # return render(request,'user/index.html')
    #  return redirect("user")  
    return redirect('image:index')

# def user_login(request):
#     if (request.method == 'POST'):
#         username = request.POST.get('username', null)
#         password = request.POST.get('password', null)
#         user = authenticate(username=username, password=password)
#         if user:
#             login(request, user)
#             messages.success(request, "Loged In Successfull" )
#             return redirect('user:profile')
#         else:
#             messages.error(request, "Check You Credentials" )
#             return redirect('user:login')
#     return render(request, 'user/login.html')

# def user_logout(request):
#     logout(request)
#     return redirect('user:login')

# def register(request): 
#     if (request.method == 'POST'):
#         username = request.POST['username']
#         password = request.POST['password']
#         # password = request.POST.get("password", null)
#         email = request.POST['email']
#         first_name = request.POST['first_name']
#         last_name = request.POST['last_name']
#         if User.objects.filter(username=username).exists():
#             messages.error(request, "User Allready exist" )
#             return render(request, 'user/register.html')
#         else:
#             user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
#             user = authenticate(username=username, password=password)
#             login(request, user)
#             messages.success(request, "Registered Successfull" )
#             return redirect('user:profile')
#     return render(request, 'user/register.html')

# # @login_required
# def profile(request):
#     data =request.user
#     if request.method == 'POST':
#         myfile = request.FILES['myfile']
#         fs = FileSystemStorage();
#         filename = fs.save(myfile.name, myfile)
#         uploaded_file_url = fs.url(filename)
#         return render(request, 'core/simple_upload.html', {
#             'uploaded_file_url': uploaded_file_url
#         })

#     return render(request, 'user/profile.html',{'data':data})

def delete(request,id):
    Image.objects.filter(id=id).delete()
    return redirect('image:index')

templates/image/index.html
{% extends 'layouts/master.html' %}

{% block title %}Image{% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Cards</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        <li class="breadcrumb-item">Components</li>
        <li class="breadcrumb-item active">Cards</li>
      </ol>
  <div class="mb-3">
    <form method="post" action="{% url 'image:store' %}" enctype="multipart/form-data">
        {% csrf_token %}
  <div class="input-group">
    <input type="file" class="form-control" name="image" id="formFile" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
    <input type="text" class="form-control" name="title" id="formFile" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
  <button class="btn btn-primary" type="submit">Save</button>

  </div>
</form>
</div>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row align-items-top">
      {% for item in page_obj %}
      <div class="col-lg-3">
       
        {% comment %} <li class="list-group-item">{{ item.id }}</li> {% endcomment %}
        <!-- Card with an image on top -->
        <div class="card">

          <div class="dropdown">
              <i class="bi bi-three-dots-vertical dropdown-toggle" data-bs-toggle="dropdown"></i>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'image:delete' id=item.id %}">deleted</a></li>
              {% comment %} <li><a class="dropdown-item" href="#">Link 2</a></li>
              <li><a class="dropdown-item" href="#">Link 3</a></li> {% endcomment %}
            </ul>
          </div>
          <img src="{{ item.src }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ item.title }}</h5>
            {% comment %} <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> {% endcomment %}
          </div>
        </div>
      </div>
      {% endfor %}
      {% include "components/pagination.html" %}
       {% comment %} <div class="col-lg-3">
        <div class="card">
          <img src="/static/assets/img/card.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card with an image on top</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="card">
          <img src="/static/assets/img/card.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card with an image on top</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="card">
          <img src="/static/assets/img/card.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card with an image on top</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div> {% endcomment %}
    </div>
  </section>


{% endblock %}